<?php
/**
 * @file
 * Definition of Zurb Foundation Two column stacked Display Suite layout.
 */

function ds_zf_2col_stacked_powerpipe1form() {
  return array(
    'label' => t('Powerpipe 1 Two column stacked for forms'),
    'regions' => array(
      'header' => t('Header'),
      'left' => t('Left'),
      'right' => t('Right'),
      'footer' => t('Footer'),
    ),
    'image' => TRUE,
  );
}
